export const EMOJIS = {
  ADDED: "📈",
  AUDIT: "📝",
  BALANCE: "💰",
  CHECKING: "⏳",
  COMMAND: "📖",
  COMMANDS: "📚",
  DATE: "📅",
  DE_RANKED: "⬇️",
  ERROR: "❌",
  FIRST_PLACE: "🥇",
  HISTORY: "📜",
  INACTIVE: "💤",
  INFO: "ℹ️",
  REASON: "❓",
  REMOVED: "📉",
  SECOND_PLACE: "🥈",
  SUCCESS: "✅",
  SUMMARY: "📊",
  THIRD_PLACE: "🥉",
  TROPHY: "🏆",
  UNDONE: "↩️",
  YAY: "🎉",
} as const;
